module.exports = [
	'React',
	'React Native',
	'React Hot Loader',
	'Preact',
	'jQuery',
	'jQuery UI',
	'Vue',
	'Svelte',
	'NPM',
	'Yarn',
	'PureML',
	'CoffeeScript',
	'TypeScript',
	'Gatsby',
	'GraphQL',
	'Ember',
	'Laravel',
	'Mootools',
	'Elm',
	'ReasonML',
	'WASM',
	'.NET Core',
	'Cordova',
	'Microsoft Teams',
	'Three.js',
	'Angular 1',
	'Angular 2',
	'MongoDB',
	'GNU/Linux',
	'Hadoop',
	'Next.js',
	'Babel',
	'Redux',
	'RxJS',
	'LitElement',
	'lit-html',
	'Bootstrap',
	'Electron',
	'Nuxt.js',
	'Webpack',
	'Rollup',
	'Parcel',
	'PostCSS',
	'Lodash',
	'Emotion',
	'MobX',
	'Verdaccio',
	'JSON:API',
	'Marko',
	'CSS Modules',
	'Workbox',
	'Riot.js',
	'Backbone',
	'GPU.js',
	'Styled JSX',
	'raxjs', // https://github.com/alibaba/rax
	'nervjs', // https://github.com/NervJS/nerv
	'infernojs', // https://infernojs.org
	'Prototype JS', // http://prototypejs.org
	'script.aculo.us' // http://script.aculo.us
];
